name: Build and Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +%Y%m%d)"
          echo "::set-output name=repository::${REPOSITORY,,}"
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Scout
        id: docker_build_scout
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.repository }}:latest
            ghcr.io/${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.date }}
          pull: true